version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./dist:/dist
            - ./site.conf:/etc/nginx/conf.d/site.conf
        depends_on:
            - php
    php:
        image: php:5.6-fpm
        volumes:
            - ./code:/code
